name: Primer workflow

on: push

jobs: 
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo Actions"

      - name: Baja codigo
        uses: actions/checkout@v5

      - name: Probar codigo
        run: python3 Main.py

      - name: Crear imagen Docker
        run: docker build -t paumtz/holamundo .

      - name: Probar contenedor Docker
        run: docker run paumtz/holamundo
        
